Flowpack:
  Task:
    # See https://symfony.com/doc/current/components/lock.html#available-stores for more options
    lockStorage: 'flock://%FLOW_PATH_TEMPORARY%/SymfonyLockStorage'
    tasks: []
    keepTaskExecutionHistory: 3
    keepRemovedTasksInTaskExecutionHistory: true
